import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NavBar } from "@/components/NavBar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Every route depends on request-scoped data (at minimum the language cookie, read via
// NavBar on every page) so there's nothing to gain from Next.js attempting a build-time
// prerender anywhere in this app. Without this, Next.js still tries a trial render of
// each route during `next build`, which renders NavBar's Prisma queries against the
// database as part of that attempt — if that query fails or times out (e.g. a strained
// connection pool during Vercel's build), the whole build fails, even though the route
// was always going to end up server-rendered on demand anyway.
export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
